### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by ameibj** [yulesj/ele-theme-tool#1]
npm WARN deprecated node-sass@4.14.1: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
npm ERR! code 1
npm ERR! path E:\SVN-app\light-platform-ui-v2-static\light-platform-ui-static\node_modules\gulp-sass\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: E:\Program Files\nodejs\node.exe E:\SVN-app\light-platform-ui-v2-static\light-platform-ui-static\node_modules\gulp-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'E:\\Program Files\\nodejs\\node.exe',
 环境又不允许更新版本； 目前是node 16.14  项目  "node-sass": "^6.0.1", "sass-loader": "^10.1.1", 这2个。换成 sass， 和会elementUI 编译出问题。真是折磨

**Comment by yulesj** [comment]
node：14.20.0
遇到node版本等问题可以初始化一个新的空项目，使用指定的node版本，定义完主题后，把主题文件夹和theme-tool-web.js 文件复制到实际项目中引用（element-ui 提供的自定义工具，其实就是生成了一个 css 目录）

**Comment by ameibj** [comment]
您好。您在帮看下再运行 掘金第三大步  node_modules/.bin/et 时报错了。 我看两下node_modules  theme-chalk里的文件已经替换好了mixToVar函数，但是在运行此命令编译报错；

 Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.

  Using browsers option can cause errors. Browserslist config
  can be used for Babel, Autoprefixer, postcss-normalize and other tools.

  If you really need to use option, rename it to overrideBrowserslist.

  Learn more at:
![error](https://github.com/user-attachments/assets/1839b385-712e-4ead-b418-3e0102477023)
非常感谢~~

**Comment by ameibj** [comment]
重新运行解决了! 感谢

**Comment by ameibj** [comment]
请问如果 本地vue组件内。使用的是 scss 的rgba（ ） 工具函数，引用的共用elelemnt-var scss变量： 
例如：background： rgba（$--color-primary， 0.5）； 这种编译会颜色显示不正确。应该是scss 语法不支持动态的原始css 变量，只接受 静态的16进制颜色。 rgba（#409EFF， 0.5）； 这种写法； 请问您有没有相应的思路；

**Comment by yulesj** [comment]
可以根据16进制的颜色生成 rgb数值 然后直接使用就行

**Comment by ameibj** [comment]
是这样的；目前在前端，我还没办法 把vue文件里的 scss rgba（）函数做调整，要么就是生成一套 原生css。 16进制和rgb的，；我选择是对局部用到scss 函数的用 现有的颜色去替代；非常敢接您百忙解答；目前已经解决了我的需求；我公司git网站很不稳定，您帖子您可关闭了。再次感谢，谢谢！




web
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yulesj/ele-theme-tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月5日(星期二) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yulesj/ele-theme-tool] 安装失败 (Issue #1)





 
可以根据16进制的颜色生成 rgb数值 然后直接使用就行

**Comment by ameibj** [comment]
大佬您好，问题是这样的：前端vue组件内使用 scss 变量&nbsp;$--color-primary-light-2 这种elementUI 的变量或者组件内使用 mixToVar($--color-white, $--color-primary, 10%)；
&nbsp;本地运行dev 模式下，自定义的组件可以正常替换成 css的变量；但生存环境，我发现生成的变量有bug；这种我感觉像编译问题；具体不知道怎么解决？


&nbsp;
